---
- name: Deploy basic configuration required by AVD to all switches and hosts
  hosts: all
  collections:
    - arista.eos

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: arista.eos.eos
    ansible_user: admin
    ansible_password: admin
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Deploy base configuration to switches
      eos_config:
        src: base-configs/common-config.cfg

- name: Deploy basic configuration to hosts
  hosts: ENDPOINTS
  gather_facts: no
  collections:
    - arista.eos

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: arista.eos.eos
    ansible_user: admin
    ansible_password: admin
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Deploy configuration to hosts
      eos_config:
        src: 'base-configs/{{ inventory_hostname }}.cfg'

