---
all:
  children:
    AVD_LAB:
      vars:
        ansible_user: avd-user
        ansible_password: 1234QWer
        # Configure privilege escalation
        ansible_become: true
        ansible_become_method: enable

      children:
        AVD_FABRIC:
          children:
            AVD_SPINES:
              vars:
                type: spine
              hosts:
                spine1:
                  ansible_host: 172.20.20.11
                spine2:
                  ansible_host: 172.20.20.12
                  
            AVD_LEAFS:
              vars:
                type: l3leaf
              children:
                pod1:
                  hosts:
                    leaf1:
                      ansible_host: 172.20.20.21
                    leaf2:
                      ansible_host: 172.20.20.22
                pod2:
                  hosts:
                    leaf3:
                      ansible_host: 172.20.20.23
                    leaf4:
                      ansible_host: 172.20.20.24

            AVD_TENANT_NETWORKS:
              children:
                AVD_LEAFS:

            AVD_SERVERS:
              children:
                AVD_LEAFS:

    ENDPOINTS:
    # These are the end-hosts, which are not covered by AVD.
    # AVD does not require or use this group, but it allows these devices to be configured through other playbooks.
      hosts:
        host1:
          ansible_host: 172.20.20.31
        host2:
          ansible_host: 172.20.20.32
