---
all:
  children:
    # cv_servers:
    #   hosts:
    #     cv:
    #       ansible_host: <replace with CVP ip or hostname>
    #       ansible_user: <replace with CVP user name>
    #       ansible_password: <replace with CVP password>
    #       cv_collection: v3
    ACEL3_LAB:
      vars:
        ansible_user: avd-user
        ansible_password: 1234QWer
        # Configure privilege escalation
        ansible_become: true
        ansible_become_method: enable

      children:
        ACEL3_FABRIC:
          children:
            ACEL3_SPINES:
              vars:
                type: spine
              hosts:
                spine1:
                  ansible_host: 172.20.20.11
                spine2:
                  ansible_host: 172.20.20.12
                spine3:
                  ansible_host: 172.20.20.13
                  
            ACEL3_LEAFS:
              vars:
                type: l3leaf
              children:
                pod1:
                  hosts:
                    leaf1:
                      ansible_host: 172.20.20.21
                    leaf2:
                      ansible_host: 172.20.20.22
                pod2:
                  hosts:
                    leaf3:
                      ansible_host: 172.20.20.23
                    leaf4:
                      ansible_host: 172.20.20.24

            ACEL3_TENANT_NETWORKS:
              children:
                ACEL3_LEAFS:

            ACEL3_SERVERS:
              children:
                ACEL3_LEAFS:
