---
all:
  children:
    # cv_servers:
    #   hosts:
    #     cv:
    #       ansible_host: <replace with CVP ip or hostname>
    #       ansible_user: <replace with CVP user name>
    #       ansible_password: <replace with CVP password>
    #       cv_collection: v3
    ACEL3_LAB:
      vars:
        ansible_user: avd-user
      children:
        ACEL3_FABRIC:
          children:
            ACEL3_SPINES:
              vars:
                type: spine
              hosts:
                spine1:
                  ansible_host: spine1
                spine2:
                  ansible_host: spine2
                spine3:
                  ansible_host: spine3
                  
            ACEL3_LEAFS:
              vars:
                type: l3leaf
              children:
                pod1:
                  hosts:
                    leaf1:
                      ansible_host: leaf1
                    leaf2:
                      ansible_host: leaf2
                pod2:
                  hosts:
                    leaf3:
                      ansible_host: leaf3
                    leaf4:
                      ansible_host: leaf4

            ACEL3_TENANT_NETWORKS:
              children:
                ACEL3_LEAFS:

            ACEL3_SERVERS:
              children:
                ACEL3_LEAFS:
