- name: Run fabric state validation
  hosts: AVD_FABRIC
  collections:
    - arista.avd
    - arista.cvp

  tasks:
    - name: run state checks on devices
      import_role:
         name: arista.avd.eos_validate_state