---
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$oCFR9c/VyAdlIFBc$izSktzY8Pj.kj3swlE/ccmHaOEJbw36GdLsoYQqqUgk2kgAI9UEkGFjXUCasEGVsTwhu7eDeDhBtw1RIqiOZs1"
  avd-user:
    privilege: 15
    role: network-admin
    sha512_password: "$6$wVJbPGK1cGLn34cO$LL5IGQ.No.LTmK2mvHqjtA.KYlloyYa0Jefj46VUaBg8cHMgZKpJM04fu/mO5o5HMEKfEIDtAJJ4Tr8AM1MDh."

# Cloud Vision server information
# cvp_instance_ip: <replace with CVP ip or hostname>
# cvp_ingestauth_key: <replace with CVP aeris ingest key>

# OOB management network default gateway.
mgmt_gateway: 172.20.20.1
# If ATD is running cEOS, management interface is Management0
mgmt_interface: Management0
mgmt_interface_vrf: default

# DNS servers.
name_servers:
  - 127.0.0.11

# DNS domain
dns_domain: clab

# AAA authentication and authorization
aaa_authentication:
  login:
    default: local
aaa_authorization:
  exec:
    default: local

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
ntp_servers:
 - 169.254.169.123

# radius_servers:
#   - host: 192.168.0.1
#     # vrf: default
#     key: 0207165218120E

# aaa_server_groups:
#   - name: atds
#     type: radius
#     servers:
#       - server: 192.168.0.1
#         # vrf: default